version: '3.8'

services:
  db:
    image: mysql:8.2.0
    container_name: local-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: devops
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - nextcloud_network

  app:
    image: nextcloud:stable-apache
    container_name: nextcloud
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: devops
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - nextcloud_network

volumes:
  db_data:
  nextcloud_data:

networks:
  nextcloud_network:
